"""empty message

Revision ID: 90669948d732
Revises: 71239f225074
Create Date: 2023-01-05 01:42:26.815309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90669948d732'
down_revision = '71239f225074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('diameter', sa.Integer(), nullable=False))
    op.drop_column('planets', 'diamenter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('diamenter', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('planets', 'diameter')
    # ### end Alembic commands ###
